changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - enhanced
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - fixed
    - title: Documentation
      labels:
        - documentation
