# Ref: https://github.com/flatpak/flatpak-github-actions

name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., v0.1.6)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-flatpak:
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install Blueprint Compiler
        run: |
          git clone https://gitlab.gnome.org/GNOME/blueprint-compiler.git ./subprojects/blueprint-compiler
          cd ./subprojects/blueprint-compiler
          meson setup build
          meson install -C build
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Elevate-${{ matrix.variant.arch }}.flatpak
          manifest-path: io.github.thecodenomad.elevate.json
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.variant.arch }}
          arch: ${{ matrix.variant.arch }}
          verbose: true
      - name: Compute SHA256
        run: |
          sha256sum Elevate-${{ matrix.variant.arch }}.flatpak > Elevate-${{ matrix.variant.arch }}.flatpak.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-${{ matrix.variant.arch }}
          path: |
            Elevate-${{ matrix.variant.arch }}.flatpak
            Elevate-${{ matrix.variant.arch }}.flatpak.sha256

  create-release:
    needs: build-flatpak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: flatpak-*
          path: artifacts
          merge-multiple: true
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ inputs.tag }}
          gh release create "$TAG" \
            --title "$TAG" \
            --notes "Stable release for $TAG\n\nFlatpak bundles for x86_64 and aarch64 with SHA256 checksums." \
            artifacts/Elevate-x86_64.flatpak \
            artifacts/Elevate-x86_64.flatpak.sha256 \
            artifacts/Elevate-aarch64.flatpak \
            artifacts/Elevate-aarch64.flatpak.sha256
