name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-flatpak:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: "Install Blueprint Compiler"
        run: |
          git clone https://gitlab.gnome.org/GNOME/blueprint-compiler.git ./subprojects/blueprint-compiler
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Elevate-${{ matrix.arch }}.flatpak
          manifest-path: io.github.thecodenomad.elevate.json
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.arch }}
          arch: ${{ matrix.arch }}
      - name: Compute SHA256
        run: |
          sha256sum Elevate-${{ matrix.arch }}.flatpak > Elevate-${{ matrix.arch }}.flatpak.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-${{ matrix.arch }}
          path: |
            Elevate-${{ matrix.arch }}.flatpak
            Elevate-${{ matrix.arch }}.flatpak.sha256

  create-release:
    needs: build-flatpak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: flatpak-*
          path: artifacts
          merge-multiple: true
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          IS_PRERELEASE=false
          if [[ $TAG == *"-pre" ]]; then
            IS_PRERELEASE=true
          fi
          gh release create "$TAG" \
            --title "$TAG" \
            --notes "Automated release for $TAG" \
            --prerelease "$IS_PRERELEASE" \
            artifacts/Elevate-x86_64.flatpak \
            artifacts/Elevate-x86_64.flatpak.sha256 \
            artifacts/Elevate-aarch64.flatpak \
            artifacts/Elevate-aarch64.flatpak.sha256
